; PlatformIO Project Configuration File

[env:genericSTM32F446RE]
platform = ststm32
board = genericSTM32F446RE
framework = stm32cube

; Build settings
build_type = debug
build_flags =
    -Og
    -g2
    -Wl,-u_printf_float

; Project structure
src_dir = Core/Src
include_dir = Core/Inc

; Upload / Debug settings
upload_protocol = stlink
debug_tool = stlink

; IMPORTANT: no hardware reset dependency (you said no NRST)
upload_flags =
    -c
    reset_config none

; Serial monitor
monitor_speed = 115200

[platformio]
src_dir = Core/Src
include_dir = Core/Inc